server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    compatibility-verifier:
      enabled: false
    config:
      server:
        native:
          search-locations: file:${CONFIG_REPO_PATH:./config-repo}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %5p [%15.15t] %-40.40logger{39} : %m%n"
