server:
  port: 8083
  ssl:
    enabled: true
    key-store: ${TLS_KEYSTORE_PATH:classpath:tls/keystore.p12}
    key-store-password: ${TLS_KEYSTORE_PASSWORD:xyzbank-dev}
    key-store-type: PKCS12
    trust-store: ${TLS_TRUSTSTORE_PATH:classpath:tls/truststore.p12}
    trust-store-password: ${TLS_TRUSTSTORE_PASSWORD:xyzbank-dev}
    trust-store-type: PKCS12
    client-auth: need
  compression:
    enabled: true

spring:
  application:
    name: bff-atm

core-service:
  base-url: ${CORE_SERVICE_BASE_URL:http://localhost:8080}
  pin-verification-base-url: ${CORE_SERVICE_PIN_VERIFICATION_BASE_URL:https://localhost:8453}
  connect-timeout-ms: 3000
  read-timeout-ms: 3000

auth-server:
  token-uri: ${AUTH_TOKEN_URI:http://localhost:9000/oauth2/token}
  client-id: ${BFF_ATM_CLIENT_ID:bff-atm}
  client-secret: ${BFF_ATM_CLIENT_SECRET:bff-atm-dev-secret}

channel-auth:
  jwt:
    secret: ${BFF_ATM_SESSION_SECRET:dev-channel-auth-jwt-signing-secret-please-rotate-in-prod}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %5p [%X{correlationId}] [%15.15t] %-40.40logger{39} : %m%n"

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
